import Head from 'next/head'
import Image from 'next/image'


import Search from '../components/Search'
import styles from '../styles/Home.module.css'
import dynamic from "next/dynamic";
import Banner from '../components/Banner';

const Header :any = dynamic(() => import('./../components/Header'), { ssr: false });


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />


      <Banner />





      
    </> 
  )
}